#!/usr/bin/env bash
# AxMem write-gate — entry-form integrity at write time. (port of the
# production gate, 4 months / ~30 caught incidents of hardening; P1 2026-09-13)
#
# Checks (all mechanical, zero judgment):
#   A  net-new oversize entries (> entry_limit bytes; [sole-record] exempts —
#      compression is only legal when the detail lives somewhere else)
#   B  Index rows == Entry headers (parity; an unindexed entry is invisible)
#   C  orphan date-list blocks outside Index (rule-bearing content must be a
#      proper entry: header + tag + ratification)
#   C2 Active dashboard size cap (injected every session = a per-turn tax)
#   C3 disguised headers (any prefix before ** blinds counting, parity,
#      retirement tracking and title-anchored retrieval at once)
#   D  namespaced definition + naked reference mix (poisons dangling scans)
#
# Body sizing counts to the NEXT header — a Ratified-line early stop lets 5KB
# ride behind a one-line footer (adversarial-audit escape, sealed 2026-09-13).
# Modes: (no arg) status + baseline refresh · --block gate (exit 2 on new debt)
#        --self-test red/green incl. both escape fixtures
set -u
. "$(dirname "${BASH_SOURCE[0]}")/../lib/prelude.sh"

LIMIT="$AXMEM_ENTRY_LIMIT"
STATE="${AXMEM_GATE_BASELINE:-$AXMEM_STATE_DIR/write-gate.baseline}"
MEM="$AXMEM_MEMORY_DIR"
DEC="$MEM/decisions.md"; LES="$MEM/lessons.md"; STD="$MEM/standinginstructions.md"
PROG="$MEM/progress.md"
PROG_LIMIT="$(axmem_cfg gates.active_dashboard_limit 3000)"

if [ "${1:-}" = "--self-test" ]; then
  T="$(mktemp -d)"
  fixture() { printf '%s' "$1" > "$T/mem/lessons.md"; }
  mkdir -p "$T/mem" "$T/state"
  printf '## Index\n\n## Entries\n' > "$T/mem/decisions.md"
  cp "$T/mem/decisions.md" "$T/mem/standinginstructions.md"
  run_gate() { AXMEM_MEMORY_DIR="$T/mem" AXMEM_GATE_BASELINE="$T/state/b" AXMEM_STATE_DIR="$T/state" bash "${BASH_SOURCE[0]}" --block </dev/null >/dev/null 2>&1; }
  ok=0
  big="$(head -c 4000 /dev/zero | tr '\0' 'x')"
  # 1 绿:合规条目过
  fixture '## Index

- 2026-01-01 [a:b] t

## Entries

**2026-01-01 — t** [a:b]
body
'
  echo 0 > "$T/state/b"; run_gate && ok=$((ok+1))
  # 2 红:裸超长必须拦
  fixture "## Index

- 2026-01-01 [a:b] t

## Entries

**2026-01-01 — t** [a:b]
$big
"
  echo 0 > "$T/state/b"; run_gate; [ $? -eq 2 ] && ok=$((ok+1))
  # 3 红(逃逸①):Ratified 行后藏正文,照拦
  fixture "## Index

- 2026-01-01 [a:b] t

## Entries

**2026-01-01 — t** [a:b]
Ratified by: x
$big
"
  echo 0 > "$T/state/b"; run_gate; [ $? -eq 2 ] && ok=$((ok+1))
  # 4 绿:[sole-record] 豁免真放行
  fixture "## Index

- 2026-01-01 [a:b] t

## Entries

**2026-01-01 — t** [a:b] [sole-record]
$big
"
  echo 0 > "$T/state/b"; run_gate && ok=$((ok+1))
  # 5 红(逃逸②):前缀伪装标题
  fixture '## Index

## Entries

> **2026-01-01 — ghost** [a:g]
body
'
  echo 0 > "$T/state/b"; run_gate; [ $? -eq 2 ] && ok=$((ok+1))
  # 6 red (escape E4): a single leading space before ** also disguises a
  # header from the same four consumers as a non-** prefix — must be caught
  fixture '## Index

## Entries

 **2026-01-01 — ghost2** [a:g2]
body
'
  echo 0 > "$T/state/b"; run_gate; [ $? -eq 2 ] && ok=$((ok+1))
  # 7 red (escape E5): wrapping an oversize body in per-line "*(...)" archive-
  # note dress beyond the first 3 free lines must still be counted, not
  # skipped for free (a 4KB entry disguised this way was measured passing)
  noteline="$(head -c 200 /dev/zero | tr '\0' 'x')"
  manylines=""
  i=0
  while [ "$i" -lt 10 ]; do manylines="${manylines}*(note $i) $noteline
"; i=$((i+1)); done
  fixture "## Index

- 2026-01-01 [a:b] t

## Entries

**2026-01-01 — t** [a:b]
${manylines}"
  echo 0 > "$T/state/b"; run_gate; [ $? -eq 2 ] && ok=$((ok+1))
  # 8/9 (escape E7): the fast path must recognize PRODUCTION-shaped hook
  # JSON — a Windows path arrives JSON-escaped, i.e. TWO literal backslash
  # characters per separator in the raw bytes. This fixture is generated by
  # a real JSON producer (node's JSON.stringify), never hand-typed through a
  # shell command: typing "\\" through a shell tool halves it before it ever
  # reaches the fixture, which is exactly how earlier audits missed this bug
  # (every fixture they fed was accidentally the already-unescaped form).
  T7="$(mktemp -d)"; mkdir -p "$T7/mem" "$T7/state" "$T7/other"
  # bad fixture: orphan date-list block outside any Index — --block must
  # return exit 2 on this content if (and only if) it actually runs.
  printf '## Index\n\n## Entries\n\n- 2026-01-01 orphan date-list block, never a proper entry\n' > "$T7/mem/lessons.md"
  : > "$T7/mem/decisions.md"; : > "$T7/mem/standinginstructions.md"
  # node is a native Windows binary — Git Bash/MSYS auto-converts a
  # POSIX-looking argument like "$T7/mem" to its Windows-drive form before
  # node ever sees it (process.argv[1] arrives already converted). Capture
  # that SAME converted form once and reuse it for both AXMEM_MEMORY_DIR and
  # the JSON path, so they name the identical directory the identical way —
  # otherwise the fixture would compare a POSIX-form $MEM against a
  # Windows-form file_path and never match regardless of the fix under test.
  MEMWIN7="$(node -e 'process.stdout.write(process.argv[1])' "$T7/mem")"
  OTHERWIN7="$(node -e 'process.stdout.write(process.argv[1])' "$T7/other")"
  # Build each JSON payload from that dir, expressed with backslash
  # separators (the Windows form), then hand it to JSON.stringify — the
  # escaping comes from that real producer, not from typed-out text.
  memjson="$(node -e '
    const p = process.argv[1].split("/").join("\\") + "\\lessons.md";
    process.stdout.write(JSON.stringify(p));
  ' "$MEMWIN7")"
  otherjson="$(node -e '
    const p = process.argv[1].split("/").join("\\") + "\\index.ts";
    process.stdout.write(JSON.stringify(p));
  ' "$OTHERWIN7")"
  printf '{"session_id":"e7","tool_name":"Edit","tool_input":{"file_path":%s}}' "$memjson" > "$T7/hook-mem.json"
  printf '{"session_id":"e7","tool_name":"Edit","tool_input":{"file_path":%s}}' "$otherjson" > "$T7/hook-other.json"
  run_gate7() { AXMEM_MEMORY_DIR="$MEMWIN7" AXMEM_STATE_DIR="$T7/state" AXMEM_GATE_BASELINE="$T7/state/b" bash "${BASH_SOURCE[0]}" --block < "$1" >/dev/null 2>&1; }
  # 8 red: JSON-escaped memory path over a bad fixture must run FULLY and
  # block (exit 2) — proves the fast path did not falsely short-circuit.
  echo 0 > "$T7/state/b"; run_gate7 "$T7/hook-mem.json"; [ $? -eq 2 ] && ok=$((ok+1))
  # 9 green: same JSON shape but a path outside the memory dir, over the SAME
  # bad fixture, must still exit 0 — the fast path still short-circuits for
  # genuinely unrelated edits (this is what makes it a fast path at all).
  echo 0 > "$T7/state/b"; run_gate7 "$T7/hook-other.json" && ok=$((ok+1))
  rm -rf "$T7"
  # 10 green (lesson-class taxonomy): a strict `Class: [[class:x]]` line is
  # metadata, not content, and must not count toward entry size — body alone
  # stays just under the limit, but adding the Class line's bytes would tip
  # it over if it were miscounted as body. classes.md must define class:x or
  # manifest's B6 (a separate, unrelated check also run by --block) would
  # block on an undefined class target rather than exercise the size skip.
  printf '**2026-09-14 — Class: x** [class:x]\nCriterion: test fixture only.\n' > "$T/mem/classes.md"
  classbody="$(head -c $((LIMIT - 5)) /dev/zero | tr '\0' 'x')"
  fixture "## Index

- 2026-01-01 [a:b] t

## Entries

**2026-01-01 — t** [a:b]
Class: [[class:x]]
${classbody}
"
  echo 0 > "$T/state/b"; run_gate && ok=$((ok+1))
  rm -rf "$T"
  if [ "$ok" -eq 10 ]; then echo "write-gate self-test 10/10"; exit 0; else echo "write-gate self-test $ok/10 FAIL"; exit 1; fi
fi

# --block fast path: when invoked as a PostToolUse hook with a file_path that
# is not under the memory dir, nothing guarded can have changed — exit free.
if [ "${1:-}" = "--block" ] && [ ! -t 0 ]; then
  # stdin timeout (porting note): a background process whose stdin is an
  # unclosed pipe makes a bare `head` block forever — hung two ops chains the
  # day this fast-path was born. No hook JSON within 1s = assume none, run the
  # full check (the fail-safe direction).
  if command -v timeout >/dev/null 2>&1; then _hin="$(timeout 1 head -c 4096 2>/dev/null || true)"; else _hin=""; fi
  # Collapse doubled slashes after the backslash->slash swap (porting note,
  # E7): production hook JSON carries a Windows path JSON-escaped, i.e. TWO
  # literal backslash characters per separator in the raw bytes (e.g.
  # "C:\\Users\\x\\.claude\\memory\\lessons.md"). `tr '\\' '/'` turns each of
  # those into a forward slash, so a doubled separator survives as a doubled
  # slash (".../memory/lessons.md" comes out "..//memory//lessons.md") and
  # never matches a single-slash needle below — every memory edit was waved
  # through as "not a memory write" and every check below was skipped. Fold
  # runs of slashes back to one before the match.
  _fp="$(printf '%s' "$_hin" | grep -o '"file_path"[[:space:]]*:[[:space:]]*"[^"]*"' | head -1 | sed 's/.*"\([^"]*\)"$/\1/' | tr '\\' '/' | sed 's#//*#/#g')"
  # Lowercase both sides before matching (porting note, E3): Windows paths are
  # case-insensitive, so a hook JSON spelling e.g. "\MEMORY\" would otherwise
  # slip past this fast path untouched and skip every check below it.
  _fpl="$(printf '%s' "$_fp" | tr 'A-Z' 'a-z')"
  _meml="$(printf '%s' "$MEM" | tr 'A-Z' 'a-z')"
  if [ -n "$_fpl" ]; then
    case "$_fpl" in
      *"$_meml"*) # memory write → full run; slurp the remaining stdin for write-echo
        if command -v timeout >/dev/null 2>&1; then _hin="$_hin$(timeout 1 cat 2>/dev/null || true)"; fi
        HOOK_JSON="$_hin" ;;
      *) exit 0 ;;
    esac
  fi
fi
HOOK_JSON="${HOOK_JSON:-}"

count_over(){ [ -f "$1" ] || { echo 0; return; }
  # Archive-note lines (*(...)*, *Archived, *RAG) are skipped so a legit
  # provenance footer doesn't inflate the previous entry's size. Skip is
  # capped at 3 lines per entry (porting note, E5): with no cap, wrapping an
  # oversize body in per-line "*(...)*" dress lets it count as 0 — measured
  # letting a 4KB entry through.
  # A strict `Class: [[class:x]]` line is free too (porting note): the
  # lesson-class taxonomy line is metadata, not content, and the exact-form
  # regex here is deliberately as narrow as CLASS_RE in manifest.cjs — B6
  # blocks any other shape of Class line, so this skip cannot be abused into
  # a free-text smuggling lane the way an unbounded skip could.
  LC_ALL=C awk -v L="$LIMIT" -v X="$AXMEM_SOLE_RECORD_MARK" '
    /^\*\*20/{if(h&&sz>L&&!ex)n++; h=$0;sz=0;sk=0;ex=index($0,X)>0;next}
    /^Class: \[\[class:[a-z0-9-]+\]\]$/{next}
    /^\*\(|^\*Archived|^\*RAG/{sk++; if(sk>3)sz+=length($0); next}
    h{sz+=length($0); if(index($0,X)>0)ex=1}
    END{if(h&&sz>L&&!ex)n++; print n+0}' "$1"; }
now=$(( $(count_over "$DEC") + $(count_over "$LES") ))

parity=""
p(){ [ -f "$1" ] || return 0
  if [ "$3" = "std" ]; then
    ix=$(awk '/^### Index/{i=1;next} /^## Entries/{i=0} i&&/^- 20/{n++} END{print n+0}' "$1")
    en=$(awk '/^## Entries/{e=1} e&&/^\*\*20/{n++} END{print n+0}' "$1")
  else
    ix=$(awk '/^## Index/{i=1;next} /^## Entries/{i=0} i&&/^- 20/{n++} END{print n+0}' "$1")
    en=$(grep -c '^\*\*20' "$1")
  fi
  [ "$ix" -ne "$en" ] && parity="$parity ${2}(Index ${ix}≠Entries ${en})"
}
p "$DEC" decisions dl; p "$LES" lessons dl; p "$STD" standing std

orphans=""
for f in "$DEC" "$LES" "$STD"; do
  [ -f "$f" ] || continue
  o=$(awk '/^## Index|^### Index/{i=1} /^## Entries/{i=0} !i&&/^- 20[0-9][0-9]-[0-9][0-9]-[0-9][0-9]/{n++} END{print n+0}' "$f")
  [ "$o" -gt 0 ] && orphans="$orphans $(basename "$f" .md)(${o})"
done

ghosts=""
for f in "$DEC" "$LES" "$STD"; do
  [ -f "$f" ] || continue
  g=$(grep -cE '^[^*[:space:]].*\*\*20[0-9][0-9]-[0-9][0-9]-[0-9][0-9][^*]*\*\*.*\[[a-z][a-z0-9-]*:' "$f" 2>/dev/null); g=${g:-0}
  # Leading-space disguise (porting note, E4): a single leading space also
  # blinds the same four consumers (count/parity/retirement/title-anchored
  # recall) as a non-** prefix does — must be caught the same way.
  g2=$(grep -cE '^[[:space:]]+\*\*20[0-9][0-9]-[0-9][0-9]-[0-9][0-9][^*]*\*\*.*\[[a-z][a-z0-9-]*:' "$f" 2>/dev/null); g2=${g2:-0}
  g=$((g+g2))
  [ "$g" -gt 0 ] && ghosts="$ghosts $(basename "$f" .md)(${g})"
done

active_bytes=0
[ -f "$PROG" ] && active_bytes=$(LC_ALL=C awk '/^## Active/{f=1;next} /^## Ledger/{f=0} f{n+=length($0)+1} END{print n+0}' "$PROG")

noprefix=""
for _t in $(grep -rho '\[\[[a-z0-9][a-z0-9._-]*\]\]' "$MEM"/*.md 2>/dev/null | tr -d '[]' | sort -u); do
  case "$_t" in *:*) continue;; esac
  grep -rqh "\[[a-z]\{1,\}:${_t}\]" "$MEM"/*.md 2>/dev/null && noprefix="$noprefix [[${_t}]]"
done

# E-sup: supersession bookkeeping — declaring Supersedes while the old entry's
# index row lacks its (superseded->) marker leaves the old version posing as
# current: the timeline-confusion incubator. Pure grep, zero judgment.
supviol=""
for _t in $(grep -hE '^[[:space:]]*Supersedes:' "$DEC" "$LES" "$STD" 2>/dev/null | grep -oE '\[\[[a-z][a-z0-9-]*:[A-Za-z0-9._-]+\]\]' | tr -d '[]' | sort -u); do
  _row=$(grep -h "^- 20[^][]*\[${_t}\]" "$DEC" "$LES" "$STD" 2>/dev/null | head -1)
  if [ -n "$_row" ] && ! printf '%s' "$_row" | grep -q 'superseded→'; then supviol="$supviol [$_t]"; fi
done

if [ "${1:-}" = "--block" ]; then
  prev=$(cat "$STATE" 2>/dev/null || echo -1)
  fail=0; msg=""
  if [ "$prev" -ge 0 ] 2>/dev/null && [ "$now" -gt "$prev" ]; then
    fail=1; msg="${msg}oversize entries grew ${prev}->${now} (limit ${LIMIT}B): compress to body+why+pointer, or mark ${AXMEM_SOLE_RECORD_MARK} when the detail has no other home (never compress fidelity away)\n"
  fi
  [ -n "$parity" ] && { fail=1; msg="${msg}index/entry parity broken:${parity}\n"; }
  [ -n "$orphans" ] && { fail=1; msg="${msg}orphan date-list blocks:${orphans}\n"; }
  [ -n "$ghosts" ] && { fail=1; msg="${msg}disguised entry headers:${ghosts} (headers must start the line with **)\n"; }
  [ "$active_bytes" -gt "$PROG_LIMIT" ] && { fail=1; msg="${msg}Active dashboard ${active_bytes}B > ${PROG_LIMIT}B (move history to the Ledger, keep status+pointers)\n"; }
  [ -n "$noprefix" ] && { fail=1; msg="${msg}naked wiki-refs with namespaced definitions:${noprefix} (write [[ns:tag]])\n"; }
  [ -n "$supviol" ] && { fail=1; msg="${msg}supersession bookkeeping missing:${supviol} — mark the old index row (superseded->...) in the same stroke\n"; }
  # E-graph: supersession-graph invariants (dangling target / cycle / marker-vs-declaration)
  if command -v node >/dev/null 2>&1; then
    _gout="$(AXMEM_MEMORY_DIR="$MEM" node "$(dirname "${BASH_SOURCE[0]}")/manifest.cjs" --check 2>/dev/null | grep '^  BLOCK' || true)"
    [ -n "$_gout" ] && { fail=1; msg="${msg}supersession-graph invariants violated:\n${_gout}\n"; }
    # R redundancy-lint: four countable proxies for "this repeats itself" —
    # R1 intra-entry >=12-char repeated phrase / R2 >=40-char shared prose with
    # another entry / R3 filler words / R4 low gzip ratio. R1/R4 block only
    # [sole-record] entries (the price of that exemption is proving the wording
    # is already minimal); R2/R3 block every new entry. Terms/contrasts/
    # identifiers recurring do not count; [redundancy-ok] is the escape hatch
    # (audited monthly).
    _rout="$(AXMEM_MEMORY_DIR="$MEM" node "$(dirname "${BASH_SOURCE[0]}")/redundancy-lint.cjs" 2>/dev/null | grep -v '^axmem redundancy-lint:' || true)"
    printf '%s' "$_rout" | grep -q 'BLOCK' && { fail=1; msg="${msg}redundancy-lint:\n${_rout}\nThree fixes, none lossy: delete the duplicate / replace with a back-reference (\"as above\") / replace with a [[tag]] link. Never synonym-swap. [redundancy-ok] escape hatch is audited monthly.\n"; }
  fi
  if [ "$fail" -eq 1 ]; then
    { echo "<!-- axmem-write-gate -->"; printf "%b" "$msg"; } >&2
    exit 2
  fi
  echo "$now" > "$STATE"
  # write-echo: after a clean pass, surface the old memories this write touched
  if [ -n "$HOOK_JSON" ] && command -v node >/dev/null 2>&1; then
    printf '%s' "$HOOK_JSON" | AXMEM_MEMORY_DIR="$MEM" node "$(dirname "${BASH_SOURCE[0]}")/write-echo.cjs" 2>/dev/null || true
  fi
  exit 0
fi

echo "$now" > "$STATE"
[ "$now" -gt 0 ] && echo "axmem write-gate: ${now} oversize entr(y|ies) tolerated as baseline (>${LIMIT}B)"
exit 0
